config/routes.rb
Rails.application.routes.draw do
  resources :currency_rates do
    collection do
      get :weekly_change
    end
  end
  root 'currency_rates#index'
  get "up" => "rails/health#show", as: :rails_health_check
  get 'currency_rates', to: 'currency_rates#index'
  get 'currency_rates/weekly_change', to: 'currency_rates#weekly_change'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/currency_rate.rb
require 'net/http'
require 'json'
require 'nokogiri'
require 'open-uri'

class CurrencyRate < ApplicationRecord
  validates :currency, presence: true
  validates :rate, numericality: { greater_than: 0 }
  def self.update_rates
    url = 'https://www.cbr.ru/scripts/XML_daily.asp'
    begin
      response = Net::HTTP.get(URI(url))
      xml_data = Nokogiri::XML(response)

      ActiveRecord::Base.transaction do
        xml_data.xpath('//ValCurs/Valute').each do |valute|
          char_code = valute.xpath('CharCode').text
          next unless ['USD', 'EUR', 'CNY'].include?(char_code)

          nominal = valute.xpath('Nominal').text.to_i
          value = valute.xpath('Value').text.gsub(',', '.').to_f

          # Проверка на уникальность записи перед сохранением
          next if CurrencyRate.exists?(currency: char_code, date: Date.today)

          CurrencyRate.create(currency: char_code, rate: value / nominal, date: Date.today)
        end
      end

      Rails.logger.info "Currency rates updated successfully."
    rescue => e
      Rails.logger.error "Error updating currency rates: #{e.message}"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/currency_rates_controller.rb
class CurrencyRatesController < ApplicationController
  def index
    # Получение данных за последний месяц
    @currency_rates = CurrencyRate.where('date >= ?', 1.month.ago).order(date: :asc)

    # Преобразование данных для графика
    prepare_chart_data
  end

  def weekly_change
    @currency_changes = CurrencyRate.where(currency: ['USD', 'EUR', 'CNY'])
                                    .where('date >= ?', 4.weeks.ago.beginning_of_week)
                                    .group_by(&:currency)
                                    .transform_values { |rates| weekly_change_calculation(rates) }
  end

  private

  def prepare_chart_data
    dates = @currency_rates.map(&:date).uniq
    usd_rates = dates.map { |date| @currency_rates.find { |rate| rate.date == date && rate.currency == 'USD' }&.rate.to_f }
    eur_rates = dates.map { |date| @currency_rates.find { |rate| rate.date == date && rate.currency == 'EUR' }&.rate.to_f }
    cny_rates = dates.map { |date| @currency_rates.find { |rate| rate.date == date && rate.currency == 'CNY' }&.rate.to_f }


    @chart_data = {
      x:   ['date'].concat(dates.map(&:to_s)),
      usd: ['USD'].concat(usd_rates),
      eur: ['EUR'].concat(eur_rates),
      cny: ['CNY'].concat(cny_rates)
    }

  end

  def weekly_change_calculation(rates)
    # Логика расчета изменения цен за каждую неделю
    rates.sort_by(&:date).group_by { |rate| rate.date.beginning_of_week }.transform_values do |weekly_rates|
      { start_of_week: weekly_rates.first.rate, end_of_week: weekly_rates.last.rate }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/currency_rates_helper.rb
module CurrencyRatesHelper
end

app/views/currency_rates/index.html.erb
<h1>Currency Rates for the Last Month</h1>

<div  data-controller="currency-rates" id="chart"
     data-currency-rates-chart-data-value="<%= @chart_data.to_json %>">
</div>

<%= link_to 'Weekly Change', weekly_change_currency_rates_path %>

app/views/currency_rates/weekly_change.html.erb
<h1>Weekly Currency Rate Changes</h1>

<% @currency_changes.each do |currency, changes| %>
  <h2><%= currency %></h2>
  <table>
    <thead>
    <tr>
      <th>Week Starting</th>
      <th>Rate at Start of Week</th>
      <th>Rate at End of Week</th>
      <th>Change</th>
    </tr>
    </thead>
    <tbody>
    <% changes.each do |week_start, rates| %>
      <tr>
        <td><%= week_start %></td>
        <td><%= rates[:start_of_week].round(2) %></td>
        <td><%= rates[:end_of_week].round(2) %></td>
        <td><%= (rates[:end_of_week] - rates[:start_of_week]).round(2) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>
<%= link_to 'Back to Main Page', currency_rates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CurrencyExchangeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>